import js from "@eslint/js";
import convexPlugin from "@convex-dev/eslint-plugin";
import tseslint from "typescript-eslint";
import { defineConfig } from "eslint/config";

/**
 * ESLint gate for the Convex backend.
 *
 * Scoped to `convex/` on purpose. The rest of the tree (apps/api, packages/*,
 * api/) is already covered by `pnpm check`, which runs the naming, encoding,
 * emoji and env-manifest scanners plus a full typecheck. The Convex plugin is
 * the only linter that understands `ctx.db` and the registered-function
 * wrappers, so it earns its place here rather than as repo-wide JS lint.
 *
 * Two of the plugin's rules need TypeScript type information:
 * `explicit-table-ids` infers the table name from `Id<"table">`, and
 * `no-collect-in-query` inspects the call's return type. So the convex block
 * below is type-aware and resolves programs through projectService, which picks
 * up convex/tsconfig.json, while the repo-wide block stays type-free for speed.
 */
export default defineConfig([
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      ".blaster/**",
      // Generated by the Convex CLI. Its contents are the compiler's output,
      // not ours, and `convex:dev` rewrites it on every push.
      "convex/_generated/**",
    ],
  },

  js.configs.recommended,
  tseslint.configs.recommended,

  // Type-free parsing for every TypeScript file, so the repo lints without
  // paying for a program build outside convex/.
  {
    files: ["**/*.ts"],
    languageOptions: {
      parser: tseslint.parser,
      ecmaVersion: 2022,
      sourceType: "module",
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // Type-aware config for the Convex backend.
  {
    files: ["convex/**/*.ts"],
    extends: [convexPlugin.configs.recommended],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Every caller authenticates with a shared secret in apps/api and most
      // public functions are reachable only from that Hono surface. There is
      // no per-user identity for a requireUser(ctx)-style check to verify, so
      // this rule has nothing to enforce and would only report noise.
      "@convex-dev/require-access-control": "off",

      // Off in the plugin's recommended set, but the rule is right for this
      // backend: an unbounded .collect() in a query reads every matching
      // document into memory and blows past the transaction limits as the
      // message and conversation tables grow.
      "@convex-dev/no-collect-in-query": "error",
    },
  },
]);
